language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

before_install:
  - yes | sdkmanager "platforms;android-27"

notifications:
  email:
    recipients:
    - victor.hidalgo.lorenzo@gmail.com
    on_success: change
    on_failure: always

script:
- chmod +x ./gradlew